# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 434a4ecd06999f2ece1a6aff307fca703632152b1a3d1d2403c4b583ca6ba26dab352ada57a688998057fd0e78ab701db01830ee1d8d9e5563bbab87533bc7bd

test:
  secret_key_base: dd0132c87ee575d02b4ac10e7f90c3a63e0aa1b75e7552958e1a7cda8f7d2ffe3df8741e6eee6fc626b6d628a2fb3e55aeb85baf96418e2927a9dd1b5b51ecab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
